# Generated by Django 6.0.6 on 2026-06-10 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_earned_points', models.IntegerField(default=0)),
                ('total_target_points', models.IntegerField(default=0)),
                ('overall_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('ممتاز', 'ممتاز (90-100)'), ('جيد', 'جيد (70-89)'), ('Warning', 'تحذير (50-69)'), ('Critical', 'حرج (<50)')], max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='performance.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المهمة')),
                ('points', models.IntegerField(default=1, verbose_name='النقاط لكل إنجاز')),
                ('daily_target', models.IntegerField(default=1, verbose_name='الهدف اليومي (الكمية المطلوبة)')),
                ('is_global', models.BooleanField(default=True, verbose_name='مهمة مشتركة للجميع؟')),
                ('assigned_employees', models.ManyToManyField(blank=True, related_name='custom_tasks', to='performance.employee', verbose_name='تخصيص لموظفين محددين')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='الكمية المنجزة')),
                ('daily_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='performance.dailyperformance')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.task')),
            ],
        ),
        migrations.CreateModel(
            name='WarningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='performance.employee')),
                ('performance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.dailyperformance')),
            ],
        ),
    ]
